name: Build Mayan Clock Widget

on:
  push:
    branches:
      - main
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --noconfirm --clean mayan_clock_widget_with_snap.spec

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: MayanClockWidget
          path: dist/MayanClockWidget/*
